In [5]:
print(df.columns)
print(df.index)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
Index(['Row1', 'Row2', 'Row3'], dtype='object')

In [4]:
data =[
    [10,20,30,40,50],
    [60,70,80,90,100],
    [110,120,130,140,150]
]

df = pd.DataFrame(data,
columns=['A','B','C','D','E'],
index=['Row1','Row2','Row3'])
display(df)
print(df.shape)

        A    B    C    D    E
Row1   10   20   30   40   50
Row2   60   70   80   90  100
Row3  110  120  130  140  150

(3, 5)

In [2]:
data = [10,20,30,40,50]
df = pd.DataFrame(data)

display(df)

    0
0  10
1  20
2  30
3  40
4  50

In [1]:
import pandas as pd

df= pd.DataFrame()
display(df)
print(df.shape)

Empty DataFrame
Columns: []
Index: []

(0, 0)