In [6]:
import pandas as pd

df = pd.DataFrame()
display(df)
print(df.shape)

Empty DataFrame
Columns: []
Index: []

(0, 0)

In [7]:
data = [10, 20, 30, 40, 50]

df = pd.DataFrame(data)

display(df)

    0
0  10
1  20
2  30
3  40
4  50

In [8]:
data = [
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150]
]

df = pd.DataFrame(
    data,
    columns=["c1", "c2", "c3", "c4", "c5"],
    index=["r1", "r2", "r3"]
)

display(df)
print(df.shape)

     c1   c2   c3   c4   c5
r1   10   20   30   40   50
r2   60   70   80   90  100
r3  110  120  130  140  150

(3, 5)

In [9]:
print(df.columns)
print(df.index)

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')
Index(['r1', 'r2', 'r3'], dtype='object')